--PROCEDURE TO CALL THE FUNCTION
CREATE OR REPLACE PROCEDURE BILL_ACTIVE_CONTRACTS(BILLING_DATE_INPUT VARCHAR2)
IS

  CURSOR GET_ACTIVE_CONTRACTS (BILLING_DATE VARCHAR2)
  IS
    SELECT
      CLIENTID,
      CONTRACT_TYPE,
      STARTDATE,
      ENDDATE
    FROM CONTRACTS
    WHERE (TO_DATE(BILLING_DATE, 'MON-YYYY') BETWEEN TO_DATE(TO_CHAR(STARTDATE, 'MON-YYYY'), 'MON-YYYY') AND TO_DATE(
        TO_CHAR(ENDDATE, 'MON-YYYY'), 'MON-YYYY'))
          OR (ENDDATE IS NULL AND STARTDATE <= TO_DATE(BILLING_DATE, 'MON-YYYY'));

  BEGIN
      FOR X IN GET_ACTIVE_CONTRACTS(BILLING_DATE_INPUT)
      LOOP
        --SELECT BILL(X.CLIENTID, X.CONTRACT_TYPE, BILLING_DATE_INPUT)
        --FROM dual;
        --INTO;
        DBMS_OUTPUT.PUT_LINE(BILL(X.CLIENTID,BILLING_DATE_INPUT, X.CONTRACT_TYPE ));

      END LOOP;

  END;
/

--EXECUTE BILL_ACTIVE_CONTRACTS('APR-2017'); 
