-------------------------------------------------------------------------------
-- procedure_script.sql
-- 		Guillermo Escobero (100346060)
-- 		Raul Olmedo Checa (100346073)
-------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE BILL_ACTIVE_CONTRACTS(BILLING_DATE_INPUT VARCHAR2)
IS

  CURSOR GET_ACTIVE_CONTRACTS (BILLING_DATE VARCHAR2)
  IS
    SELECT
      CLIENTID,
      CONTRACT_TYPE,
      STARTDATE,
      ENDDATE,
      CONTRACTID
    FROM CONTRACTS
    WHERE (TO_DATE(BILLING_DATE, 'MON-YYYY') BETWEEN TO_DATE(TO_CHAR(STARTDATE, 'MON-YYYY'), 'MON-YYYY') AND TO_DATE(
        TO_CHAR(ENDDATE, 'MON-YYYY'), 'MON-YYYY'))
          OR (ENDDATE IS NULL AND STARTDATE <= TO_DATE(BILLING_DATE, 'MON-YYYY'));

  BEGIN
    FOR X IN GET_ACTIVE_CONTRACTS(BILLING_DATE_INPUT)
    LOOP
      INSERT INTO INVOICES VALUES
        (X.CONTRACTID, TO_NUMBER(TO_CHAR(TO_DATE(BILLING_DATE_INPUT, 'MON-YYYY'), 'MM'), '99'),
         TO_NUMBER(TO_CHAR(TO_DATE(BILLING_DATE_INPUT, 'MON-YYYY'), 'YYYY'), '9999'), SYSDATE,
         BILL(X.CLIENTID, BILLING_DATE_INPUT, X.CONTRACT_TYPE));
    END LOOP;
  END;
/

--EXECUTE BILL_ACTIVE_CONTRACTS('APR-2016');
