-- 1
SELECT DISTINCT CLIENTS.SURNAME, CLIENTS.NAME, CONTRACTS.STARTDATE, CONTRACTS.ENDDATE, PRODUCTS.TYPE
FROM CONTRACTS
INNER JOIN CLIENTS ON CONTRACTS.CLIENTID=CLIENTS.CLIENTID
INNER JOIN PRODUCTS ON CONTRACTS.CONTRACT_TYPE=PRODUCTS.PRODUCT_NAME
WHERE (SYSDATE BETWEEN CONTRACTS.STARTDATE AND CONTRACTS.ENDDATE)
OR (CONTRACTS.ENDDATE IS NULL AND CONTRACTS.STARTDATE<=SYSDATE) 
ORDER BY CLIENTS.SURNAME, CLIENTS.NAME ASC;
-- 4423 rows

-- 2
SELECT * FROM (
SELECT DISTINCT ACTOR, COUNT(CASTS.TITLE)
FROM CASTS
INNER JOIN MOVIES ON CASTS.TITLE=MOVIES.MOVIE_TITLE
WHERE MOVIES.COUNTRY='USA'
GROUP BY ACTOR
ORDER BY COUNT(CASTS.TITLE) DESC
) WHERE ROWNUM<=5;
-- Robert De Niro	45
-- Morgan Freeman	36
-- Bruce Willis		35
-- Matt Damon		35
-- Steve Buscemi	33
